# Generated by Django 5.2.5 on 2025-08-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified_at',
            new_name='email_verified_at',
        ),
    ]
