# Generated by Django 5.2.5 on 2025-09-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_rename_verified_at_user_email_verified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_landlord',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='other_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tenant',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_tenant'], name='idx_users_is_tenant'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_manager'], name='idx_users_is_manager'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_manager', False), ('is_tenant', True)), models.Q(('is_manager', True), ('is_tenant', False)), models.Q(('is_manager', False), ('is_tenant', False)), _connector='OR'), name='users_one_role_ck'),
        ),
    ]
