# Generated by Django 5.2.5 on 2025-09-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_full_name_user_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='other_name',
            new_name='other_names',
        ),
    ]
