# Generated by Django 5.2.5 on 2025-09-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_permission_managerprofile_landlordprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
