# Generated by Django 5.2.5 on 2025-09-11 09:48

from django.db import migrations

def seed_permissions(apps, schema_editor):
    Permission = apps.get_model("users","Permission")
    RolePermission = apps.get_model("users", "RolePermission")

    # Define initial permissions
    initial_permissions = [
        ("can_view_users", "View users list"),
        ("can_manage_users", "Add/update/delete users"),
        ("can_view_tenant_profiles", "Can view tenant profiles"),
        ("can_manage_tenant_profiles", "Can create/update/delete tenant profiles"),
        ("can_view_manager_profiles", "Can view manager profiles"),
        ("can_manage_manager_profiles", "Can create/update/delete manager profiles"),
        ("can_manage_properties", "Can manage properties"),
        ("can_assign_property_managers", "Can assign managers to properties"),
        ("can_delete_users", "Can soft-delete users"),
    ]

    perm_objs = {}

    for code, desc in initial_permissions:
        perm, _ = Permission.objects.get_or_create(code=code, defaults={"description": desc})
        perm_objs[code] = perm
    
    # Link defaults to roles
    default_role_map = {
        "landlord": [
            "can_manage_tenant_profiles",
            "can_view_tenant_profiles",
            "can_manage_manager_profiles",
            "can_view_manager_profiles",
            "can_manage_properties",
            "can_assign_property_managers",
            "can_delete_users",
        ],
        "property_manager": [
            "can_view_tenant_profiles",
            "can_view_manager_profiles",
        ],
        "tenant": [
            "can_view_tenant_profiles",  # only their own via has_object_permission
        ],
    }

    for role, codes in default_role_map.items():
        for code in codes:
            RolePermission.objects.get_or_create(
                role=role,
                permission = perm_objs[code]
            )

def unseed_permissions(apps, schema_editor):
    Permission = apps.get_model("users", "Permission")
    RolePermission = apps.get_model("users", "RolePermission")

    codes = [
        "can_view_tenant_profiles",
        "can_manage_tenant_profiles",
        "can_view_manager_profiles",
        "can_manage_manager_profiles",
        "can_manage_properties",
        "can_assign_property_managers",
        "can_delete_users",
        "can_view_users",
        "can_manage_users"
    ]

    RolePermission.objects.filter(permission__code__in=codes).delete()
    Permission.objects.filter(code__in=codes).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_landlordprofile_is_active_tenantprofile_is_active'),
    ]

    operations = [
        migrations.RunPython(seed_permissions, unseed_permissions),
    ]
