# Generated by Django 5.2.5 on 2026-05-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seed_initial_permissions'),
    ]

    operations = [
    ]
