# Generated by Django 5.2.5 on 2026-05-18 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_seed_property_permissions'),
        ('users', '0010_seed_property_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermission',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='properties.property'),
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', True)), fields=('user', 'permission'), name='uniq_global_user_permission'),
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('user', 'permission', 'property'), name='uniq_property_user_permission'),
        ),
    ]
