# Generated by Django 5.2.5 on 2026-05-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_seed_property_permissions'),
        ('users', '0011_userpermission_created_at_userpermission_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanager',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='properties.property'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='propertymanager',
            constraint=models.UniqueConstraint(fields=('property', 'user'), name='unique_property_user'),
        ),
    ]
